language: scala
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache/coursier
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
scala:
  - 2.12.10
  - 2.13.1
jdk:
  - oraclejdk8
  - openjdk8
env:
  - SCALAJS=true
  - SCALAJS=false
script:
  - if [[ "$SCALAJS" == true ]];
    then sbt ++$TRAVIS_SCALA_VERSION validateJS;
    else sbt ++$TRAVIS_SCALA_VERSION validateJVM;
    fi
before_install:
  - pip install --user codecov
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f56e0cf8b3d780bd65c3
    on_success: change
    on_failure: always
    on_start: never
